[package]
name = "importing_local_rust_bigint"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-bigint = {path = "../../rust-bigint"}
num-traits = "0.2.18"
